repository_type: pipeline
nf_core_version: "2.14.1"
lint:
  # No multiqc support for now
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
  files_unchanged:
    - lib/NfcoreTemplate.groovy
    - .prettierignore
    # Skip warning for a removed a reference to nf-test
    - .github/PULL_REQUEST_TEMPLATE.md
