lint:
  actions_ci: false
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/nf-core-pixelator_logo_light.png
    # Ignore this for now since we haven't switched the name of the
    # main branch to main from master yet
    - .github/PULL_REQUEST_TEMPLATE.md
  multiqc_config: false
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: Pixelgen Technologies AB
  description: Pipeline for analysis of Molecular Pixelation assays
  force: false
  is_nfcore: true
  name: pixelator
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - multiqc
    - igenomes
  version: 1.5.0dev
